Repository sumory/orange, pull requests merged in 2019-03, with the labels that each got.

#146 add jwt plugins
  dashboard/routes/dashboard.lua
  dashboard/static/js/jwt_auth.js
  dashboard/views/common/left_nav.html
  dashboard/views/jwt_auth/credential-add.html
  dashboard/views/jwt_auth/credential-edit.html
  dashboard/views/jwt_auth/credential-tmpl.html
  dashboard/views/jwt_auth/jwt_auth.html
  install/orange-v0.6.4.sql
  orange/orange.lua
  orange/plugins/divide/handler.lua
  orange/plugins/jwt_auth/README.md
  orange/plugins/jwt_auth/api.lua
  orange/plugins/jwt_auth/handler.lua
Labels: v0.7.0

#229 修改 to_rewrite set_uri 时带有参数，修正参数开始位置匹配正则
  orange/plugins/rewrite/handler.lua
Labels: bugfix

#230 Update README.md
  orange/plugins/property_rate_limiting/README.md
Labels: enhancement

#231 JWT 插件安装说明
  orange/plugins/jwt_auth/README.md
Labels: enhancement

#237 hotfix jwt plugin
  orange/plugins/jwt_auth/README.md
Labels: bugfix

#234 统一使用Obejct作为基类，并且__call用于创建实例，new用于构建实例属性
  conf/orange.conf.example
  orange/store/mysql_db.lua
  orange/store/mysql_store.lua
Labels: enhancement
